# Generated by Django 5.0 on 2024-06-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("skulbus_routes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="end_latitude",
            field=models.DecimalField(
                decimal_places=6, max_digits=16, null=True, verbose_name="Route End Latitude"
            ),
        ),
        migrations.AddField(
            model_name="route",
            name="end_longitude",
            field=models.DecimalField(
                decimal_places=6, max_digits=16, null=True, verbose_name="Route End Longitude"
            ),
        ),
        migrations.AddField(
            model_name="route",
            name="start_latitude",
            field=models.DecimalField(
                decimal_places=6, max_digits=16, null=True, verbose_name="Route Start Latitude"
            ),
        ),
        migrations.AddField(
            model_name="route",
            name="start_longitude",
            field=models.DecimalField(
                decimal_places=6,
                max_digits=16,
                null=True,
                verbose_name="Route Start Longitude",
            ),
        ),
    ]
