# Generated by Django 5.0 on 2024-06-23 21:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("skulbus_routes", "0002_route_end_latitude_route_end_longitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="busstop",
            name="latitude",
            field=models.DecimalField(
                decimal_places=8, max_digits=16, verbose_name="Latitude"
            ),
        ),
        migrations.AlterField(
            model_name="busstop",
            name="longitude",
            field=models.DecimalField(
                decimal_places=8, max_digits=16, verbose_name="Longitude"
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="end_latitude",
            field=models.DecimalField(
                decimal_places=8, max_digits=16, null=True, verbose_name="Route End Latitude"
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="end_longitude",
            field=models.DecimalField(
                decimal_places=8, max_digits=16, null=True, verbose_name="Route End Longitude"
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="start_latitude",
            field=models.DecimalField(
                decimal_places=8, max_digits=16, null=True, verbose_name="Route Start Latitude"
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="start_longitude",
            field=models.DecimalField(
                decimal_places=8,
                max_digits=16,
                null=True,
                verbose_name="Route Start Longitude",
            ),
        ),
    ]
