# Generated by Django 4.0 on 2024-03-30 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skulbus_buses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='model',
            field=models.CharField(max_length=140, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='reg_number',
            field=models.CharField(max_length=20, verbose_name='Registration Number'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='seats',
            field=models.IntegerField(verbose_name='Number of Seats'),
        ),
    ]
