# Generated by Django 4.0 on 2024-05-01 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skulbus_routes', '0001_initial'),
        ('skulbus_buses', '0002_alter_bus_model_alter_bus_reg_number_alter_bus_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bus_route', to='skulbus_routes.route', verbose_name='Route'),
        ),
    ]
