# Generated by Django 4.1 on 2024-03-25 23:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("skulbus_schools", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
    ]
