# Generated by Django 5.0 on 2024-06-23 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("skulbus_routes", "0001_initial"),
        ("skulbus_students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="route",
            field=models.OneToOneField(
                blank=True,
                default="757394d72ce64928a0b4eb42b9177266",
                on_delete=django.db.models.deletion.CASCADE,
                to="skulbus_routes.route",
            ),
            preserve_default=False,
        ),
    ]
