# Generated by Django 4.0 on 2024-03-27 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skulbus_students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'export', 'import'), 'get_latest_by': 'modified', 'ordering': ('-modified', '-created'), 'verbose_name': 'Student', 'verbose_name_plural': 'Student'},
        ),
    ]
