# Generated by Django 5.0 on 2024-06-23 11:40

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("skulbus_students", "0002_student_route"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                always_update=True,
                default="frd-aman",
                editable=False,
                populate_from="lastname",
                unique=True,
            ),
            preserve_default=False,
        ),
    ]
