# Generated by Django 5.0 on 2024-06-23 11:44

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("skulbus_students", "0003_student_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                always_update=True,
                editable=False,
                populate_from="lastname",
                unique=True,
                verbose_name="Verification",
            ),
        ),
    ]
