# Generated by Django 5.0 on 2024-06-23 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("skulbus_parents", "0001_initial"),
        ("skulbus_students", "0005_studenttrip"),
    ]

    operations = [
        migrations.AddField(
            model_name="studenttrip",
            name="parent",
            field=models.OneToOneField(
                blank=True,
                default="bf001f6cba4a4b239aa3d3015a5f75f2",
                on_delete=django.db.models.deletion.CASCADE,
                to="skulbus_parents.parent",
            ),
            preserve_default=False,
        ),
    ]
