# Generated by Django 5.0 on 2024-06-23 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("skulbus_parents", "0001_initial"),
        ("skulbus_students", "0006_studenttrip_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studenttrip",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="skulbus_parents.parent",
            ),
        ),
    ]
