# Generated by Django 5.0 on 2024-06-23 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("skulbus_students", "0008_alter_studenttrip_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="studenttrip",
            name="bus_stop",
            field=models.CharField(max_length=120, null=True, verbose_name="Bus Stop"),
        ),
    ]
