# Generated by Django 5.0 on 2024-06-23 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("skulbus_routes", "0003_alter_busstop_latitude_alter_busstop_longitude_and_more"),
        ("skulbus_students", "0009_studenttrip_bus_stop"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studenttrip",
            name="bus_stop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="skulbus_routes.busstop",
                verbose_name="Bus Stop",
            ),
        ),
    ]
