# Generated by Django 5.0 on 2024-06-23 22:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("skulbus_students", "0010_alter_studenttrip_bus_stop"),
    ]

    operations = [
        migrations.AddField(
            model_name="studenttrip",
            name="bus_stop_name",
            field=models.CharField(max_length=120, null=True, verbose_name="Bus Stop"),
        ),
    ]
